{% set version = "3.0.1" %}

package:
  name: robotstatuschecker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotstatuschecker/robotstatuschecker-{{ version }}.tar.gz
  sha256: 4a761a0d59c0a764d479364855f045aba371ecf94a69a43e6f378bd0592a9112

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - robotframework >=5

test:
  imports:
    - robotstatuschecker

about:
  home: https://github.com/robotframework/statuschecker
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/apache-2.0.txt
  summary: |
    Tool for validating that executed Robot Framework test cases have expected
    statuses and log messages.

  description: |
    StatusChecker is a tool for validating that executed Robot Framework test
    cases have expected statuses and log messages. It is mainly useful for
    Robot Framework test library developers who want to use Robot Framework to
    also test their libraries.

extra:
  recipe-maintainers:
    - bollwyvl
