{% set version = "2.2.0" %}

package:
  name: robotstatuschecker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/robotstatuschecker/robotstatuschecker-{{ version }}.tar.gz
  sha256: 46e0092cf52712d03d217aa0135a17a3a15c637ce5220de4044da1f939300421

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - robotframework

test:
  imports:
    - robotstatuschecker

about:
  home: https://github.com/robotframework/statuschecker
  license: Apache-2.0
  license_family: Apache
  license_file: {{ environ["RECIPE_DIR"] }}/apache-2.0.txt
  summary: |
    Tool for validating that executed Robot Framework test cases have expected
    statuses and log messages.

  description: |
    StatusChecker is a tool for validating that executed Robot Framework test
    cases have expected statuses and log messages. It is mainly useful for
    Robot Framework test library developers who want to use Robot Framework to
    also test their libraries.

extra:
  recipe-maintainers:
    - bollwyvl
