{% set name = "robotstatuschecker" %}
{% set version = "1.4" %}
{% set sha256 = "c606eebdf2f28063dcb483e43fd6bc511e84e99a9f7d004163a180be558e58f6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - robotframework

test:
  imports:
    - robotstatuschecker

about:
  home: https://github.com/robotframework/statuschecker
  license: Apache-2.0
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/apache-2.0.txt'
  summary: |
    Tool for validating that executed Robot Framework test cases have expected
    statuses and log messages.

  doc_url: http://robotframework.org/SeleniumLibrary/SeleniumLibrary.html
  dev_url: https://github.com/robotframework/SeleniumLibrary
  description: |
    StatusChecker is a tool for validating that executed Robot Framework test
    cases have expected statuses and log messages. It is mainly useful for
    Robot Framework test library developers who want to use Robot Framework to
    also test their libraries. StatusChecker 1.3 and newer are compatible both
    with Python 2 and Python 3.

extra:
  recipe-maintainers:
    - bollwyvl
