# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "4.1.0"

package:
  name: robotstatuschecker
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/r/robotstatuschecker/robotstatuschecker-${{ version }}.tar.gz
  sha256: f56647c15d285e05d82d0e8bd1a3cc5d0b645f8a02498e2457a7e02f4371d150

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - robotframework >=5

tests:
  - python:
      pip_check: true
      python_version: ${{ python_min }}.*
      imports: robotstatuschecker

about:
  license: Apache-2.0
  license_file: apache-2.0.txt
  summary: |
    Tool for validating that executed Robot Framework test cases have expected
    statuses and log messages.
  description: |
    StatusChecker is a tool for validating that executed Robot Framework test
    cases have expected statuses and log messages. It is mainly useful for
    Robot Framework test library developers who want to use Robot Framework to
    also test their libraries.
  homepage: https://github.com/robotframework/statuschecker

extra:
  recipe-maintainers:
    - bollwyvl
