travis:
  secure:
    BINSTAR_TOKEN: PxTY8GiyBvfT30LCz1Idoob3oFjMF4sZxkSONQpt4vHPw60Bs3Vb+b4xd0gCbr2xGU5EIoO9PiKunBaC4PrsfbY5Cw3adpZGZkSqLHWEQEkS3+f3YKIZzDptETMGoEWYzUX2rZXbKNcKOJrEQqDvBnJDk9fLd2WnMlY30INqEFXhF8hwjMzqxK0pfJAD+gPRgxI+kJJ7k6AW98MP6aYfFqNC6+L+aoW5ZZpQI+KnwzMf2ItItIYinzjXvyQl3cp98gbCBq/tGmOjz0m9xfBDUItdgwny7SPC0Vp7dBEFX0TqBGYW6/0ChAtNgZ9ixQlzbGIlQsLxO51ZmYSGjHS9rOPxDUtZEiNDjArUDrTrBa0laYAKsZAN+HD+gJapI9U+Sx3dl5aQXYNCBNjlhTT1jaeEWD7W/3UNx/PpqEfE+RJRrg2rtM3gPT+zbjPZYfMoMiEddan2Tonf3V+JUWaFzMJT/+DSKMlekykLzkHfm4FlKvZx7ONj4QCWfMaDNPk7KAjYVhsSNHKrUi8yoauyTagMsxUQ8nDZE28aMk1Az9y4fQdcf++Ol5hGFsI3i3yinmbg7DGkafpMG4QLVXGgWVEntquUZbNH70dX5UFMRsN6PHb36/VMz0Ng+59dkL+mzL7rXVM8XFn/jyF6qnxlU33UAngw3B1L1V8babJn4T8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
