travis:
  secure:
    BINSTAR_TOKEN: EX8fFKSxSiz1pP4B8/A6C1Ahp9AZw/JWNexz+v5WWpcUo0el9P/onDIlwde8hL9xIczSLx6FRT/4SGwYGyNDmWEqXasRPHGJ4GzkjkkzfirDFVmrHHzX5EFW5R2g7GrpD0poY4dO9YtQ65D+25NntsUhhGJCZ4tnhBuo4+1wEoR2xpjLKm21viOd3uvuThPvc3ILOTgHi8Hj6xj85Ef2KJP2L8Aqv+SwoOFxSFRz5fYWspl/oFDFn2gFwF7Y+PUaQdxrwYiBF4I/z+swCnnt7e7AaVz2w+WK3kd1JvmG4z8zQCQA70BAIpdw/67sFpmb9YRyuB+hc3eOHjFuSqV7ezzr10dsQkhDX4tm0uNZomccPcmPQ9s1P+qa1+ALDZkvMn+OroYRXbofIPi9VbSX8szOLN5ulq/LbTYdHYzVtC6AIN9ORMWbaNjozt7tzDxhtZAkkYgeCdqOGfMrEmQ/kk58sOfMZNuOgGNvS7d8Z5LzqWtRRiGnMstVBpJ7m3G86oFiEyhXy8dYDALVwJpqE98kfIn+OPRuVSSjmVvFHoOVrKVfcXG3oDAEhWUqbTS2Jya7MQg7wdSx+neBqBBLTql0HJS8uOme7uIEfGO7bKF+C+mXoa4C3fZNUR84YMfh6EM5CKRC0doMG6QH1Xv18qiHGASuQ/8Fp/tmoE2ztF0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
